name: Build and Release APK

on:
  push:
    tags:
      - 'v*'  # 只有当推送标签以 v 开头时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew assembleRelease

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            appnes/build/outputs/apk/release/appnes-release.apk  # 添加 APK 的路径
            appgg/build/outputs/apk/release/appgg-release.apk  # 添加 APK 的路径
            appgbc/build/outputs/apk/release/appgbc-release.apk  # 添加 APK 的路径
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 提供的 token
